### ISSUE TITLE
Exception when take a picture with the camera lens covered

### ISSUE THREAD

**Issue by mauriciolima88** [mReady/photopicker#1]
When taking a picture with the camera lens covered (all black) the following exception is generated:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.uberdomarlon.rebu, PID: 5586
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=123, result=-1, data=null} to activity {com.uberdomarlon.rebu/net.mready.picker.PhotoPickerActivity}: java.lang.NullPointerException: Attempt to get length of null array
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4520)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4563)
        at android.app.ActivityThread.-wrap22(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
     Caused by: java.lang.NullPointerException: Attempt to get length of null array
        at java.io.FileOutputStream.write(FileOutputStream.java:296)
        at android.support.media.ExifInterface$ByteOrderedDataOutputStream.write(ExifInterface.java:6349)
        at android.support.media.ExifInterface.writeExifSegment(ExifInterface.java:5999)
        at android.support.media.ExifInterface.saveJpegAttributes(ExifInterface.java:5156)
        at android.support.media.ExifInterface.saveAttributes(ExifInterface.java:4304)
        at net.mready.picker.BitmapUtils.processImage(BitmapUtils.java:113)
        at net.mready.picker.PhotoPickerActivity.handleResult(PhotoPickerActivity.java:197)
        at net.mready.picker.PhotoPickerActivity.onActivityResult(PhotoPickerActivity.java:180)
        at android.app.Activity.dispatchActivityResult(Activity.java:7295)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4516)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4563) 
        at android.app.ActivityThread.-wrap22(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6776) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by bogdanflorianmihai** [comment]
It seems that when writing exif data, in some cases the thumbnail is corrupt and the ExifInterface tries to write it anyway but the thumbnail data is null. I added a check to prevent the write of exif data if the thumbnail is null and I'll submit an issue to the android support team.

The fix is included in 1.0.9. If you still encounter the crash feel free to open another issue.
Thanks
